# Site settings
title: Sunil Pentapati
twitter_username: spentapati
name: Sunil pentapati

# Build settings
#markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://pentapati.blogspot.com
 - title: GitHub
   url: https://github.com/sunilpentapati
 - title: LinkedIn
   url: https://www.linkedin.com/in/pentapati

#Any buzzword skills you want to include
skills:
 - Product Strategy
 - Software Engineering
 - Agile Leadership
 - Digital Transformation
 - SaaS/Cloud Operations
 - Platform/Infrastructure Engineering
 - DevOps
 - DevSecOps
 - Multi-tenant SaaS authentication and authorization
 - Continuous Integration, Continuous Deployment, Continuous Delivery, Canary Deployments
 - High availability, disaster tolerance
 - Tech Architecture

#Work experience is required
roles:
 - title: Director, Platform Operations
   start: 207
   end: Ongoing
   employer: Fractal Industries
   description: Fractal provides the premier collaborative decision-support platform to address the world's most demanding problems. Our unique blend of data analytics-as-a-service enhanced with next-generation simulation modeling, deep learning, and artificial intelligence capabilities enables robust decision-making in an increasingly uncertain, complex and competitive world. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, DC/OS, a variety of Machine Learning techniques.
 - title: Head, DevOps Engineering
   start: 2014
   end: 2017
   employer: EMC Corp
   description: Software Development, DevOps, EngOps, Security, Service Delivery@Scale
 - title: Sr, Manager Engineering
   start: 2012
   end: 2014
   employer: Constant Contact
   description: SaaS, Development Operations, Technical Operations
 - title:  Manager Engineering
   start: 2007
   end: 2012
   employer: RSA, Security Division of EMC
   description: Application Development, Global Development Operations, Infrastructure Engineering
 - title:  Staff Engineer
   start: 2005
   end: 2007
   employer: IBM
   description: 
 - title:  Sr. Software Engineer
   start: 2003
   end: 2005
   employer: RSA
   description: 
 - title:  Consultant
   start: 2003
   end: 2003
   employer: Capital One
   description: 
 - title:  Sr. Software Engineer
   start: 1999
   end: 2002
   employer: Sybase
   description: Lead Release Engineering for PowerBuilder 8.0
 - title:  Consultant Developer
   start: 1997
   end: 1999
   employer: Autozone
   description: On-Site Lead and played a critical role in the Design, and Development of Auto-zone's corporate application systems.
 - title:  Sr. Software Engineer
   start: 1995
   end: 1997
   employer: NIIT
   description: Systems engineer at NIIT’S Business Solutions Group developing & providing support for PowerBuilder and Sybase SQL Server products


#Education is required
education:
 - level: Executive Education
   date: 2015
   subject: Executive Certificate in Management & Leadership
   school: MIT
 - level: Master of Business Adminisration (MBA)
   date: 2011
   subject: Strategy, Innovation, Leadership
   school: Olin School of Business, Babson College
 - level: Master of Science (M.Sc.)
   date: 1997
   subject: Computer Science
   school: Andhra University


#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - sunilpentapati/kafka-manager
 - sunilpentapati/osquery-configuration

theme: jekyll-theme-architect
